Repository suover/fit-on, pull requests merged in 2024-08, with the labels that each got.

#226 🐛 Fix: 프로필 이미지 처리 기능 수정
  src/main/java/com/spring/myapp/mypage/service/UserInfoService.java
  src/main/reactfront/src/components/common/comment/StyledCommentItem.tsx
  src/main/reactfront/src/components/common/profileImage/ProfileImage.tsx
  src/main/reactfront/src/pages/information/Info.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
Labels: 🐛 BugFix

#228 ✨ Feat: 마이페이지 댓글 관리 기능 구현
  src/main/java/com/spring/myapp/mypage/controller/CommentManagementController.java
  src/main/java/com/spring/myapp/mypage/dto/CommentManagementDto.java
  src/main/java/com/spring/myapp/mypage/repository/CommentManagementRepository.java
  src/main/java/com/spring/myapp/mypage/service/CommentManagementService.java
  src/main/reactfront/src/pages/mypage/CommentManagementPage.tsx
  src/main/reactfront/src/pages/mypage/PostManagementPage.tsx
  src/main/resources/mapper/mypage/CommentManagementMapper.xml
Labels: ✨ Feature

#229 ✨ Feat: 정보 게시판 글 삭제시 관련 댓글 삭제 #225
  src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardController.java
  src/main/java/com/spring/myapp/informationBoard/repository/InfoMapper.java
  src/main/java/com/spring/myapp/informationBoard/service/InfoService.java
  src/main/reactfront/src/pages/mall/Mall.tsx
  src/main/resources/mapper/informationBoard/InfoMapper.xml
Labels: ✨ Feature

#232 📃Docs : Update README.md #230
  README.md
Labels: 📃 Docs

#233 🐛 Fix : 정보글 등록 경로 에러 해결 #231
  src/main/reactfront/src/pages/administrator/PostRegisterPage.tsx
Labels: 🐛 Bug, 🐛 BugFix

#240 🐛 Fix : 정보글 수정 관련 에러 해결 #239
  src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardController.java
  src/main/reactfront/src/pages/administrator/PostRegisterPage.tsx
Labels: 🐛 Bug, 🐛 BugFix, ♻️ Refactor

#241 ✨ Feat: 마이페이지 배송지 관리 기능 구현
  src/main/java/com/spring/myapp/mypage/controller/CommentManagementController.java
  src/main/java/com/spring/myapp/mypage/controller/PostManagementController.java
  src/main/java/com/spring/myapp/mypage/controller/UserShippingAddressController.java
  src/main/java/com/spring/myapp/mypage/dto/CommentManagementDTO.java
  src/main/java/com/spring/myapp/mypage/dto/PostManagementDTO.java
  src/main/java/com/spring/myapp/mypage/dto/UserShippingAddressDTO.java
  src/main/java/com/spring/myapp/mypage/repository/CommentManagementRepository.java
  src/main/java/com/spring/myapp/mypage/repository/PostManagementRepository.java
  src/main/java/com/spring/myapp/mypage/repository/UserShippingAddressRepository.java
  src/main/java/com/spring/myapp/mypage/service/CommentManagementService.java
  src/main/java/com/spring/myapp/mypage/service/PostManagementService.java
  src/main/java/com/spring/myapp/mypage/service/UserShippingAddressService.java
  src/main/reactfront/src/pages/mypage/OneToOneInquiryPage.tsx
  src/main/reactfront/src/pages/mypage/OrderHistoryPage.tsx
  src/main/reactfront/src/pages/mypage/ProductInquiryPage.tsx
  src/main/reactfront/src/pages/mypage/ProductReviewPage.tsx
  src/main/reactfront/src/pages/mypage/ReturnAndExchangePage.tsx
  src/main/reactfront/src/pages/mypage/ShippingAddressPage.tsx
  src/main/resources/mapper/mypage/CommentManagementMapper.xml
  src/main/resources/mapper/mypage/PostManagementMapper.xml
  src/main/resources/mapper/mypage/UserShippingAddressMapper.xml
Labels: ✨ Feature

#245 🛠️ Chore: 배포 및 CI/CD 환경 설정 완료
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/spring/myapp/common/controller/HealthCheckController.java
  src/main/java/com/spring/myapp/common/controller/WebController.java
  src/main/java/com/spring/myapp/config/WebConfig.java
  src/main/java/com/spring/myapp/user/controller/NaverAuthController.java
  src/main/reactfront/package.json
  src/main/reactfront/public/index.html
  src/main/reactfront/src/components/ListTable/ListTable.styles.ts
  src/main/reactfront/src/components/ListTable/StyledColumn.styles.ts
  src/main/reactfront/src/components/ListTable/StyledColumn.tsx
  src/main/reactfront/src/pages/mypage/MyHome.tsx
  src/main/resources/application.yml
Labels: ⚙ Setting, 🌏 Deploy

#247 🐛 Fix: React 빌드 실패 문제 해결
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/main/quickBtn/QuickBtns.tsx
  src/main/resources/static/index.html
Labels: 🐛 BugFix

#253 ✨ Feat: 스크롤 관련 파일 추가 #252
  src/main/reactfront/src/components/common/ScrollToTop.tsx
  src/main/reactfront/src/index.tsx
Labels: ✨ Feature, ♻️ Refactor

#254 📃 Docs : Readme 시연용 GIF 추가 #251
  README.md
Labels: 📃 Docs
