Repository suover/fit-on, pull requests merged in 2024-05, with the labels that each got.

#14 ✨ Feat: 목록 테이블과 검색창 및 페이징 #13
  src/main/reactfront/src/components/common/search/SearchBox.tsx
  src/main/reactfront/src/components/common/search/styles.ts
  src/main/reactfront/src/components/genericTable/GenericTable.tsx
  src/main/reactfront/src/components/genericTable/styles.ts
  src/main/reactfront/src/components/icons/DeleteIcon.tsx
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
  src/main/resources/static/static/css/main.e6c13ad2.css
  src/main/resources/static/static/css/main.e6c13ad2.css.map
  src/main/resources/static/static/js/main.32457438.js
  src/main/resources/static/static/js/main.32457438.js.LICENSE.txt
  src/main/resources/static/static/js/main.32457438.js.map
Labels: ✨ Feature, 💄 Design

#16 ✨ Feat : Quill 에디터 #15
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/@types/quill-image-resize-module-react.d.ts
  src/main/reactfront/src/components/common/Editor.tsx
  src/main/reactfront/tsconfig.json
Labels: ✨ Feature

#18 ✨ Feat: SideNavbar 구현 #17
  src/main/reactfront/src/components/layout/sideNavBar/NavbarItem.ts
  src/main/reactfront/src/components/layout/sideNavBar/SideNavbar.tsx
  src/main/reactfront/src/components/layout/sideNavBar/StyledAvatar.tsx
Labels: ✨ Feature, 💄 Design

#20 ✨ Feat: 카드형 게시글, 게시판, 개별 상품 UI 제작
  src/main/reactfront/src/components/cardList/CardList.tsx
  src/main/reactfront/src/components/contentCard/ContentCard.styles.ts
  src/main/reactfront/src/components/contentCard/ContentCard.tsx
  src/main/reactfront/src/components/productItem/ProductItem.styles.ts
  src/main/reactfront/src/components/productItem/ProductItem.tsx
Labels: ✨ Feature, 💄 Design

#22 🚚 Rename: 컴포넌트 스타일 파일명 변경 #21
  src/main/reactfront/src/components/common/search/SearchBox.styles.ts
  src/main/reactfront/src/components/common/search/SearchBox.tsx
  src/main/reactfront/src/components/genericTable/GenericTable.styles.ts
  src/main/reactfront/src/components/genericTable/GenericTable.tsx
Labels: 🎨 Style

#24 🚚 Rename: 컴포넌트 파일명, 폴더 구조 변경
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/layout/footer/Footer.styles.ts
  src/main/reactfront/src/components/layout/footer/Footer.tsx
  src/main/reactfront/src/components/layout/header/Header.styles.ts
  src/main/reactfront/src/components/layout/header/Header.tsx
Labels: 🎨 Style

#26 ♻️ Refactor: GenericTable TableHead 코드 수정 #25
  src/main/reactfront/src/components/genericTable/GenericTable.tsx
Labels: ♻️ Refactor

#28 ♻️ Refactor: SideNavbar SideNavbarProps 코드 수정 #27
  src/main/reactfront/src/components/layout/sideNavBar/SideNavbar.tsx
Labels: ♻️ Refactor

#30 ♻️ Refactor: 카드 컴포넌트, 카드 리스트 코드 수정
  src/main/reactfront/src/components/cardList/CardList.tsx
  src/main/reactfront/src/components/contentCard/ContentCard.tsx
Labels: ♻️ Refactor

#42 ✨ Feat: 버튼 Component #40
  src/main/reactfront/src/components/common/genericButton/GenericButton.styles.ts
  src/main/reactfront/src/components/common/genericButton/GenericButton.tsx
Labels: ✨ Feature, 💄 Design

#39 ✨ Feat: 게시판 댓글 및 답글 Component
  src/main/reactfront/src/components/common/authorInfo/AuthorInfo.tsx
  src/main/reactfront/src/components/common/comment/CommentComponent.tsx
  src/main/reactfront/src/components/common/comment/CommentLeave.tsx
  src/main/reactfront/src/components/common/comment/CommentList.tsx
  src/main/reactfront/src/components/common/comment/CommentsTemplate.tsx
Labels: ✨ Feature, 💄 Design

#43 🐛 Fix: GenericTable props 경고 메시지 수정 #41
  src/main/reactfront/src/components/genericTable/GenericTable.styles.ts
Labels: 🐛 BugFix

#46 :sparkles: Feat: 운동 루틴 정보 페이지 #32
  src/main/reactfront/src/components/common/SelectBox.tsx
  src/main/reactfront/src/components/common/button/ButtonLikePost.tsx
  src/main/reactfront/src/components/common/button/ButtonNewRoutine.tsx
  src/main/reactfront/src/components/common/button/ButtonShare.tsx
  src/main/reactfront/src/components/common/comment/CommentComponent.tsx
  src/main/reactfront/src/components/common/comment/CommentLeave.tsx
  src/main/reactfront/src/components/common/comment/CommentList.tsx
  src/main/reactfront/src/components/common/comment/CommentsTemplate.tsx
  src/main/reactfront/src/components/contentCard/ContentCard.tsx
  src/main/reactfront/src/components/routine/RoutineBestList.tsx
  src/main/reactfront/src/components/routine/RoutineCard.tsx
  src/main/reactfront/src/components/routine/RoutineTotalList.tsx
  src/main/reactfront/src/components/routine/ViewRoutine.tsx
  src/main/reactfront/src/pages/routine/NewRoutine.tsx
  src/main/reactfront/src/pages/routine/RoutineMain.tsx
  src/main/reactfront/src/pages/routine/ViewRoutineDetail.tsx
  src/main/reactfront/src/types/DummyData.tsx
Labels: ✨ Feature, ♻️ Refactor, 💄 Design

#49 ✨ Feat: 회원가입 페이지 화면 구현 #7
  src/main/reactfront/src/pages/Signup/SignupPage.styles.ts
  src/main/reactfront/src/pages/Signup/SignupPage.tsx
  src/main/reactfront/src/styles/Signup/SignupPage.ts
Labels: ✨ Feature, 💄 Design

#50 💄 Design: 마이페이지 화면 레이아웃 수정 #48
  src/main/reactfront/src/components/calendar/Calendar.styles.ts
  src/main/reactfront/src/pages/mypage/MyHome.tsx
  src/main/reactfront/src/pages/mypage/MyPageLayout.tsx
Labels: 💄 Design

#55 ✨ Feat: 리스트형 테이블 제작
  src/main/reactfront/src/components/ListTable/ListTable.styles.ts
  src/main/reactfront/src/components/ListTable/ListTable.tsx
  src/main/reactfront/src/components/ListTable/StyledColumn.styles.ts
  src/main/reactfront/src/components/ListTable/StyledColumn.tsx
Labels: ✨ Feature, 💄 Design

#53 ✨ Feature: 커뮤니티 페이지 화면
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/common/button/ButtonCategoryTag.tsx
  src/main/reactfront/src/components/common/button/ButtonNewPost.tsx
  src/main/reactfront/src/components/community/Board.tsx
  src/main/reactfront/src/components/community/ViewPost.tsx
  src/main/reactfront/src/components/layout/footer/Footer.tsx
  src/main/reactfront/src/components/layout/header/Header.tsx
  src/main/reactfront/src/components/routine/RoutineBestList.tsx
  src/main/reactfront/src/components/routine/RoutineTotalList.tsx
  src/main/reactfront/src/index.css
  src/main/reactfront/src/index.tsx
  src/main/reactfront/src/pages/community/CommunityMain.tsx
  src/main/reactfront/src/pages/community/NewPost.tsx
  src/main/reactfront/src/pages/community/ViewPostDetail.tsx
Labels: ✨ Feature, ♻️ Refactor, 💄 Design

#57 ✨ Feat: 메인 페이지 제작 #5
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/assets/img/main/banner.jpg
  src/main/reactfront/src/assets/img/main/loop.jpg
  src/main/reactfront/src/assets/img/main/product1.jpg
  src/main/reactfront/src/assets/img/main/product2.jpg
  src/main/reactfront/src/assets/img/main/product3.jpg
  src/main/reactfront/src/assets/img/main/routine1.jpg
  src/main/reactfront/src/assets/img/main/routine2.jpg
  src/main/reactfront/src/assets/img/main/routine3.jpg
  src/main/reactfront/src/components/main/bestItems/BestItems.styles.ts
  src/main/reactfront/src/components/main/bestItems/BestItems.tsx
  src/main/reactfront/src/components/main/community/MainCommuity.tsx
  src/main/reactfront/src/components/main/info/MainInfo.styles.ts
  src/main/reactfront/src/components/main/info/MainInfo.tsx
  src/main/reactfront/src/components/main/quickBtn/QuickBtn.styles.ts
  src/main/reactfront/src/components/main/quickBtn/QuickBtn.tsx
  src/main/reactfront/src/components/main/quickBtn/QuickBtns.styles.ts
  src/main/reactfront/src/components/main/quickBtn/QuickBtns.tsx
  src/main/reactfront/src/components/main/routine/MainRoutines.styles.ts
  src/main/reactfront/src/components/main/routine/MainRoutines.tsx
  src/main/reactfront/src/components/main/routine/RoutineList.styles.ts
  src/main/reactfront/src/components/main/routine/RoutineList.tsx
  src/main/reactfront/src/components/main/tabBtn/TabBtn.styles.ts
  src/main/reactfront/src/components/main/tabBtn/TabBtn.tsx
  src/main/reactfront/src/pages/main/Main.tsx
  src/main/reactfront/src/styles/main/Main.styles.ts
  src/main/reactfront/src/types/MainDummyData.ts
Labels: ✨ Feature, 💄 Design

#63 ✨ Feat: 고객센터 페이지 제작 #35
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/components/contentDetail/ContentDetail.styles.ts
  src/main/reactfront/src/components/contentDetail/ContentDetail.tsx
  src/main/reactfront/src/components/csCenter/FAQ/FAQListItem.styles.ts
  src/main/reactfront/src/components/csCenter/FAQ/FAQListItem.tsx
  src/main/reactfront/src/components/csCenter/FAQ/FAQLists.styles.ts
  src/main/reactfront/src/components/csCenter/FAQ/FAQLists.tsx
  src/main/reactfront/src/components/csCenter/checkBox/CheckBox.styles.ts
  src/main/reactfront/src/components/csCenter/checkBox/CheckBox.tsx
  src/main/reactfront/src/components/csCenter/inquiry/inquiryList/InquiryListItem.tsx
  src/main/reactfront/src/components/csCenter/inquiry/inquiryList/InquiryLists.tsx
  src/main/reactfront/src/components/csCenter/inquiry/inquiryList/inquiryListItem.styles.ts
  src/main/reactfront/src/components/csCenter/inquiry/inquiryList/inquiryLists.styles.ts
  src/main/reactfront/src/components/csCenter/inquiry/newInquiry/NewInquiryModal.styles.ts
  src/main/reactfront/src/components/csCenter/inquiry/newInquiry/NewInquiryModal.tsx
  src/main/reactfront/src/pages/csCenter/ClientService.tsx
  src/main/reactfront/src/pages/csCenter/Event.tsx
  src/main/reactfront/src/pages/csCenter/EventDetail.tsx
  src/main/reactfront/src/pages/csCenter/FAQ.tsx
  src/main/reactfront/src/pages/csCenter/Inquiry.tsx
  src/main/reactfront/src/pages/csCenter/Notice.tsx
  src/main/reactfront/src/pages/csCenter/NoticeDetail.tsx
  src/main/reactfront/src/styles/csCenter/ClientServie.styles.ts
  src/main/reactfront/src/styles/csCenter/FAQ.styles.ts
  src/main/reactfront/src/styles/csCenter/Inquiry.styles.ts
  src/main/reactfront/src/types/MainDummyData.ts
Labels: ✨ Feature, 💄 Design

#65 ✨ Feat: 클라이언트 사이드 라우팅을 위해 WebConfig 추가 #64
  src/main/java/com/spring/myapp/config/WebConfig.java
Labels: ✨ Feature

#70 🐛 Fix: React Router 경로 문제로 빈 화면이 발생하는 이슈 수정 #69
  src/main/java/com/spring/myapp/config/WebConfig.java
Labels: 🐛 BugFix

#71 ✨ Feat: AWS S3 클라이언트 설정을 위한 S3Config 클래스 및 의존성 추가 #67
  build.gradle
  src/main/java/com/spring/myapp/config/S3Config.java
Labels: ✨ Feature

#74 🐛 Fix : BABEL BUG fix #73
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
Labels: 🐛 BugFix

#76 ✨ Feat: SpringDoc OpenAPI 의존성 추가 및 Swagger UI 설정 #75
  build.gradle
Labels: ✨ Feature

#78 ✨ Feat: 정보 페이지 제작 #34
  src/main/reactfront/src/components/information/CommentInputField.styles.ts
  src/main/reactfront/src/components/information/CommentInputField.tsx
  src/main/reactfront/src/components/information/CommentList.tsx
  src/main/reactfront/src/components/information/CommentListItem.tsx
  src/main/reactfront/src/components/information/StyledCommentItem.styles.ts
  src/main/reactfront/src/components/information/StyledCommentItem.tsx
  src/main/reactfront/src/pages/information/Info.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
  src/main/reactfront/src/styles/information/Info.styles.ts
  src/main/reactfront/src/styles/information/InfoDetail.styles.ts
  src/main/reactfront/src/types/MainDummyData.ts
Labels: ✨ Feature, 💄 Design

#80 ✨ Feat: 라우터 구성 #62
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/assets/img/csCenter/checkbox-01.png
  src/main/reactfront/src/assets/img/information/infobanner1.jpg
  src/main/reactfront/src/assets/img/signin/google.png
  src/main/reactfront/src/assets/img/signin/kakao.png
  src/main/reactfront/src/assets/img/signin/naver.png
  src/main/reactfront/src/components/common/button/ButtonNewPost.tsx
  src/main/reactfront/src/components/community/Board.tsx
  src/main/reactfront/src/components/csCenter/checkBox/CheckBox.styles.ts
  src/main/reactfront/src/components/layout/header/Header.tsx
  src/main/reactfront/src/components/main/quickBtn/QuickBtns.tsx
  src/main/reactfront/src/components/productCard/ProductCard.tsx
  src/main/reactfront/src/components/routine/RoutineCard.tsx
  src/main/reactfront/src/components/routine/RoutineTotalList.tsx
  src/main/reactfront/src/index.tsx
  src/main/reactfront/src/pages/Signin/SigninPage.tsx
  src/main/reactfront/src/pages/mall/Mall.tsx
  src/main/reactfront/src/pages/mall/Products.tsx
  src/main/reactfront/src/pages/mypage/MyPageLayout.tsx
  src/main/reactfront/src/styles/information/Info.styles.ts
  src/main/reactfront/src/styles/main/Main.styles.ts
  src/main/reactfront/src/types/MainDummyData.ts
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: ✨ Feature, 🎨 Style

#82 🚚 Rename: mall 파일명 변경 #81
  src/main/reactfront/src/pages/mall/Fittness.tsx
  src/main/reactfront/src/pages/mall/Food.tsx
  src/main/reactfront/src/pages/mall/Supplemnet.tsx
Labels: 🐛 BugFix

#87 ✨ Feature: 주문 페이지 화면 구현 #37
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/order/OrderInfoProps.tsx
  src/main/reactfront/src/components/order/Radio.tsx
  src/main/reactfront/src/components/order/SelectAccount.tsx
  src/main/reactfront/src/components/order/SelectCard.tsx
  src/main/reactfront/src/components/productDetail/PurchasePanel.styles.ts
  src/main/reactfront/src/components/productDetail/PurchasePanel.tsx
  src/main/reactfront/src/components/productDetail/QuantityInput.tsx
  src/main/reactfront/src/components/productDetail/UnstyledSelectForm.tsx
  src/main/reactfront/src/components/tab/ReviewCombine.tsx
  src/main/reactfront/src/pages/Order/orderPage.tsx
  src/main/reactfront/src/pages/productDetail/productDetail.tsx
  src/main/reactfront/src/styles/order/Order.Styles.ts
  src/main/reactfront/src/styles/productDetail/productDetail.styles.ts
  src/main/reactfront/src/types/orderInterface.tsx
Labels: ✨ Feature, 💄 Design

#88 ✨ Feat: 나의 루틴 페이지 화면 구현
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/order/OrderInfoProps.tsx
  src/main/reactfront/src/components/order/Radio.tsx
  src/main/reactfront/src/components/order/SelectAccount.tsx
  src/main/reactfront/src/components/order/SelectCard.tsx
  src/main/reactfront/src/components/productDetail/PurchasePanel.styles.ts
  src/main/reactfront/src/components/productDetail/PurchasePanel.tsx
  src/main/reactfront/src/components/productDetail/QuantityInput.tsx
  src/main/reactfront/src/components/productDetail/UnstyledSelectForm.tsx
  src/main/reactfront/src/components/tab/ReviewCombine.tsx
  src/main/reactfront/src/pages/Order/orderPage.tsx
  src/main/reactfront/src/pages/admin/AdminPage.tsx
  src/main/reactfront/src/pages/admin/ItemListPage.tsx
  src/main/reactfront/src/pages/admin/ItemRegisterPage.tsx
  src/main/reactfront/src/pages/admin/PostListPage.tsx
  src/main/reactfront/src/pages/admin/PostRegisterPage.tsx
  src/main/reactfront/src/pages/mypage/MyRoutinePage.tsx
  src/main/reactfront/src/pages/mypage/MyRoutinesPage.tsx
  src/main/reactfront/src/pages/mypage/SharedRoutinePage.tsx
  src/main/reactfront/src/pages/productDetail/productDetail.tsx
  src/main/reactfront/src/styles/order/Order.Styles.ts
  src/main/reactfront/src/styles/productDetail/productDetail.styles.ts
  src/main/reactfront/src/types/orderInterface.tsx
Labels: ✨ Feature, ♻️ Refactor, 💄 Design

#90 📝 Docs : 삭제된 파일 복구 및 파일 수정 및 변경#89
  gradlew
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/assets/itemRegister/noImage.jpeg
  src/main/reactfront/src/components/order/OrderInfoProps.tsx
  src/main/reactfront/src/components/order/Radio.tsx
  src/main/reactfront/src/components/order/SelectAccount.tsx
  src/main/reactfront/src/components/order/SelectCard.tsx
  src/main/reactfront/src/pages/Order/orderPage.tsx
  src/main/reactfront/src/pages/Signin/SigninPage.tsx
  src/main/reactfront/src/pages/Signup/SignupPage.styles.ts
  src/main/reactfront/src/pages/Signup/SignupPage.tsx
  src/main/reactfront/src/pages/administrator/AdminPage.tsx
  src/main/reactfront/src/pages/administrator/CommunityListPage.tsx
  src/main/reactfront/src/pages/administrator/EtcInquiryListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemInquiryListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemRegisterPage.tsx
  src/main/reactfront/src/pages/administrator/MemberListPage.tsx
  src/main/reactfront/src/pages/administrator/PostListPage.tsx
  src/main/reactfront/src/pages/administrator/PostRegisterPage.tsx
  src/main/reactfront/src/pages/administrator/ReviewListPage.tsx
  src/main/reactfront/src/styles/Signup/SignupPage.ts
  src/main/reactfront/src/styles/administrator/AdminPage.styles.ts
  src/main/reactfront/src/styles/administrator/CommunityListPage.styles.ts
  src/main/reactfront/src/styles/administrator/EtcInquiryListPage.styles.ts
  src/main/reactfront/src/styles/administrator/ItemInquiryListPage.styles.ts
  src/main/reactfront/src/styles/administrator/ItemListPage.styles.ts
  src/main/reactfront/src/styles/administrator/MemberListPage.styles.ts
  src/main/reactfront/src/styles/administrator/PostListPage.styles.ts
  src/main/reactfront/src/styles/administrator/ReviewListPage.styles.ts
  src/main/reactfront/src/styles/order/Order.Styles.ts
  src/main/reactfront/src/styles/productDetail/productDetail.styles.ts
  src/main/reactfront/src/types/administrator/CommunityData.tsx
  src/main/reactfront/src/types/administrator/EtcInquiryDatat.tsx
  src/main/reactfront/src/types/administrator/InformationData.tsx
  src/main/reactfront/src/types/administrator/ItemInquiryData.tsx
  src/main/reactfront/src/types/administrator/ItemsData.tsx
  src/main/reactfront/src/types/administrator/ReviewData.tsx
  src/main/reactfront/src/types/administrator/membersData.tsx
  src/main/reactfront/src/types/orderInterface.tsx
Labels: 📃 Docs

#93 🐛 Fix: 파일명 대소문자 변경이 안되는 상황 해결 #92
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/csCenter/inquiry/inquiryList/InquiryListItem.styles.ts
  src/main/reactfront/src/components/csCenter/inquiry/inquiryList/InquiryListItem.tsx
  src/main/reactfront/src/components/csCenter/inquiry/inquiryList/InquiryLists.styles.ts
  src/main/reactfront/src/components/csCenter/inquiry/inquiryList/InquiryLists.tsx
  src/main/reactfront/src/components/order/OrderInfoProps.tsx
  src/main/reactfront/src/components/productDetail/ImageDetail.tsx
  src/main/reactfront/src/components/productDetail/PurchasePanel.tsx
  src/main/reactfront/src/components/tab/MoreViewBtn.tsx
  src/main/reactfront/src/components/tab/ProductDescription.tsx
  src/main/reactfront/src/components/tab/QuestionBoard.tsx
  src/main/reactfront/src/components/tab/QuestionModal.tsx
  src/main/reactfront/src/components/tab/ReviewCombine.tsx
  src/main/reactfront/src/components/tab/Tab.tsx
  src/main/reactfront/src/pages/mall/Fittness.tsx
  src/main/reactfront/src/pages/mall/Food.tsx
  src/main/reactfront/src/pages/mall/Mall.tsx
  src/main/reactfront/src/pages/mall/Products.tsx
  src/main/reactfront/src/pages/mall/Supplemnet.tsx
  src/main/reactfront/src/pages/order/OrderPage.tsx
  src/main/reactfront/src/pages/productDetail/ProductDetail.tsx
  src/main/reactfront/src/pages/signin/SigninPage.tsx
  src/main/reactfront/src/pages/signup/SignupPage.tsx
  src/main/reactfront/src/styles/productDetail/ProductDetail.styles.ts
  src/main/reactfront/src/styles/signin/SigninPage.styles.ts
  src/main/reactfront/src/styles/signup/SignupPage.styles.ts
  src/main/reactfront/src/types/OrderInterface.tsx
  src/main/reactfront/src/types/ProductData.ts
  src/main/reactfront/src/types/Question.ts
  src/main/reactfront/src/types/ReviewData.ts
Labels: 🐛 BugFix

#96 ✨ Feature: 장바구니 페이지 화면 구현 #95
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/pages/order/OrderPage.tsx
  src/main/reactfront/src/pages/shoppingBasket/ShoppingBasketPage.tsx
  src/main/reactfront/src/styles/shoppingBasket/ShoppingBasket.styles.ts
  src/main/reactfront/src/types/OrderInterface.tsx
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: ✨ Feature, ♻️ Refactor, 💄 Design

#97 💄 Design: 일부 페이지 디자인 통합 및 수정 #86
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/common/TopBtn.tsx
  src/main/reactfront/src/components/common/sidebar/SidebarWrapper.tsx
  src/main/reactfront/src/components/productCard/ProductCard.styles.ts
  src/main/reactfront/src/components/productCard/ProductCard.tsx
  src/main/reactfront/src/components/productDetail/ProductExplain.tsx
  src/main/reactfront/src/components/productDetail/PurchasePanel.styles.ts
  src/main/reactfront/src/components/productDetail/PurchasePanel.tsx
  src/main/reactfront/src/pages/administrator/AdminPage.tsx
  src/main/reactfront/src/pages/administrator/CommunityListPage.tsx
  src/main/reactfront/src/pages/administrator/EtcInquiryListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemInquiryListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemRegisterPage.tsx
  src/main/reactfront/src/pages/administrator/MemberListPage.tsx
  src/main/reactfront/src/pages/administrator/PostListPage.tsx
  src/main/reactfront/src/pages/administrator/PostRegisterPage.tsx
  src/main/reactfront/src/pages/administrator/ReviewListPage.tsx
  src/main/reactfront/src/pages/csCenter/ClientService.tsx
  src/main/reactfront/src/pages/mall/Fittness.tsx
  src/main/reactfront/src/pages/mall/Food.tsx
  src/main/reactfront/src/pages/mall/Mall.tsx
  src/main/reactfront/src/pages/mall/Supplemnet.tsx
  src/main/reactfront/src/pages/productDetail/ProductDetail.tsx
  src/main/reactfront/src/styles/administrator/AdminPage.styles.ts
  src/main/reactfront/src/styles/administrator/MemberListPage.styles.ts
  src/main/reactfront/src/styles/csCenter/ClientServie.styles.ts
  src/main/reactfront/src/styles/signin/SigninPage.styles.ts
  src/main/reactfront/src/styles/signup/SignupPage.styles.ts
Labels: ♻️ Refactor, 💄 Design

#101 🛠️ Chore: .gitignore 파일 업데이트 #100
  .gitignore
Labels: ⚙ Setting

#102 ✨ Feature: 이메일/비밀번호 찾기 페이직 구현 #99
  src/main/reactfront/src/pages/signin/SigninPage.tsx
  src/main/reactfront/src/pages/signup/SignupPage.tsx
Labels: ✨ Feature, ♻️ Refactor, 💄 Design

#104 🛠️ Chore: .gitignore 파일 업데이트 #103
  .gitignore
Labels: ⚙ Setting

#105 ✨ Feat: Spring Security와 JWT 및 회원가입 기능 구현 #83
  build.gradle
  src/main/java/com/spring/myapp/config/SecurityConfig.java
  src/main/java/com/spring/myapp/security/JwtAuthenticationFilter.java
  src/main/java/com/spring/myapp/security/JwtTokenProvider.java
  src/main/java/com/spring/myapp/user/controller/UserController.java
  src/main/java/com/spring/myapp/user/model/User.java
  src/main/java/com/spring/myapp/user/repository/UserMapper.java
  src/main/java/com/spring/myapp/user/service/UserDetailsServiceImpl.java
  src/main/java/com/spring/myapp/user/service/UserService.java
  src/main/reactfront/.gitignore
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/api/axiosConfig.ts
  src/main/reactfront/src/pages/signup/SignupPage.tsx
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: ✨ Feature

#108 🛠️ Chore: Spring Boot DevTools 추가 #107
  build.gradle
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: ⚙ Setting

#110 ✨ Feat: 이메일과 비밀번호로 로그인 기능 구현 #109
  src/main/java/com/spring/myapp/config/SecurityConfig.java
  src/main/java/com/spring/myapp/security/JwtAuthenticationFilter.java
  src/main/java/com/spring/myapp/security/JwtTokenProvider.java
  src/main/java/com/spring/myapp/user/controller/UserController.java
  src/main/java/com/spring/myapp/user/model/LoginRequest.java
  src/main/java/com/spring/myapp/user/service/UserService.java
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/layout/header/Header.tsx
  src/main/reactfront/src/context/AuthContext.tsx
  src/main/reactfront/src/pages/signin/SigninPage.tsx
  src/main/resources/static/index.html
Labels: ✨ Feature

#111 ✨ Feature: 프론트 통합 디자인 및 UI 수정 #106
  src/main/reactfront/src/components/common/search/SearchBox.styles.ts
  src/main/reactfront/src/components/common/sidebar/SidebarWrapper.tsx
  src/main/reactfront/src/components/contentDetail/ContentDetail.tsx
  src/main/reactfront/src/components/main/quickBtn/QuickBtns.tsx
  src/main/reactfront/src/components/productDetail/PurchasePanel.tsx
  src/main/reactfront/src/pages/administrator/AdminPage.tsx
  src/main/reactfront/src/pages/administrator/ItemListPage.tsx
  src/main/reactfront/src/pages/administrator/MemberListPage.tsx
  src/main/reactfront/src/pages/administrator/PostListPage.tsx
  src/main/reactfront/src/pages/administrator/ReviewListPage.tsx
  src/main/reactfront/src/pages/community/CommunityMain.tsx
  src/main/reactfront/src/pages/mall/Mall.tsx
  src/main/reactfront/src/pages/mypage/CommentManagementPage.tsx
  src/main/reactfront/src/pages/mypage/MyPageLayout.tsx
  src/main/reactfront/src/pages/mypage/MyRoutinePage.tsx
  src/main/reactfront/src/pages/mypage/MyRoutinesPage.tsx
  src/main/reactfront/src/pages/mypage/OneToOneInquiryPage.tsx
  src/main/reactfront/src/pages/mypage/OrderHistoryPage.tsx
  src/main/reactfront/src/pages/mypage/PostManagementPage.tsx
  src/main/reactfront/src/pages/mypage/ReturnAndExchangePage.tsx
  src/main/reactfront/src/pages/mypage/SharedRoutinePage.tsx
  src/main/reactfront/src/styles/administrator/ItemListPage.styles.ts
  src/main/reactfront/src/styles/administrator/PostListPage.styles.ts
  src/main/reactfront/src/styles/signin/SigninPage.styles.ts
  src/main/reactfront/src/types/administrator/membersData.tsx
  src/main/resources/static/index.html
Labels: ✨ Feature, ♻️ Refactor, 💄 Design

#113 💄 Design: 디자인, 컴포넌트 통합 및 수정#98
  src/main/reactfront/src/components/cardList/CardList.tsx
  src/main/reactfront/src/components/common/authorInfo/AuthorInfo.tsx
  src/main/reactfront/src/components/common/button/ButtonCategoryTag.tsx
  src/main/reactfront/src/components/common/button/ButtonLikePost.tsx
  src/main/reactfront/src/components/common/button/ButtonNewRoutine.tsx
  src/main/reactfront/src/components/common/button/ButtonShare.tsx
  src/main/reactfront/src/components/common/comment/CommentComponent.tsx
  src/main/reactfront/src/components/common/comment/CommentInputField.styles.ts
  src/main/reactfront/src/components/common/comment/CommentInputField.tsx
  src/main/reactfront/src/components/common/comment/CommentLeave.tsx
  src/main/reactfront/src/components/common/comment/CommentList.tsx
  src/main/reactfront/src/components/common/comment/CommentListItem.tsx
  src/main/reactfront/src/components/common/comment/CommentsTemplate.tsx
  src/main/reactfront/src/components/common/comment/StyledCommentItem.styles.ts
  src/main/reactfront/src/components/common/comment/StyledCommentItem.tsx
  src/main/reactfront/src/components/community/Board.tsx
  src/main/reactfront/src/components/community/ViewPost.tsx
  src/main/reactfront/src/components/information/CommentList.tsx
  src/main/reactfront/src/components/listTable/ListTable.styles.ts
  src/main/reactfront/src/components/listTable/ListTable.tsx
  src/main/reactfront/src/components/listTable/StyledColumn.styles.ts
  src/main/reactfront/src/components/listTable/StyledColumn.tsx
  src/main/reactfront/src/components/main/community/MainCommuity.tsx
  src/main/reactfront/src/components/main/info/MainInfo.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.styles.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.tsx
  src/main/reactfront/src/components/routine/RoutineBestList.tsx
  src/main/reactfront/src/components/routine/RoutineCard.tsx
  src/main/reactfront/src/components/routine/RoutineTotalList.tsx
  src/main/reactfront/src/components/routine/ViewRoutine.tsx
  src/main/reactfront/src/components/swiper/SwiperList.styles.ts
  src/main/reactfront/src/components/swiper/SwiperList.tsx
  src/main/reactfront/src/pages/community/CommunityMain.tsx
  src/main/reactfront/src/pages/community/NewPost.tsx
  src/main/reactfront/src/pages/community/ViewPostDetail.tsx
  src/main/reactfront/src/pages/csCenter/Event.tsx
  src/main/reactfront/src/pages/csCenter/Notice.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
  src/main/reactfront/src/pages/main/Main.tsx
  src/main/reactfront/src/pages/routine/NewRoutine.tsx
  src/main/reactfront/src/pages/routine/RoutineMain.tsx
  src/main/reactfront/src/pages/routine/ViewRoutineDetail.tsx
  src/main/reactfront/src/styles/main/Main.styles.ts
Labels: ♻️ Refactor, 💄 Design

#118 💄 Design: 마이페이지, 일부 styles 파일 수정 #116
  package-lock.json
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/ListTable/ListTable.tsx
  src/main/reactfront/src/components/common/sidebar/SidebarWrapper.tsx
  src/main/reactfront/src/components/community/Board.tsx
  src/main/reactfront/src/components/layout/header/Header.tsx
  src/main/reactfront/src/components/listTable/ListTable.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.styles.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.tsx
  src/main/reactfront/src/pages/csCenter/Event.tsx
  src/main/reactfront/src/pages/csCenter/Notice.tsx
  src/main/reactfront/src/pages/mypage/MyPageLayout.tsx
  src/main/reactfront/src/pages/mypage/MyRoutinePage.tsx
  src/main/reactfront/src/pages/mypage/MyRoutinesPage.tsx
  src/main/reactfront/src/pages/mypage/SharedRoutinePage.tsx
  src/main/reactfront/src/styles/administrator/MemberListPage.styles.ts
  src/main/resources/static/index.html
Labels: ♻️ Refactor, 💄 Design

#120 ✨ Feature: 상품Create
  src/main/java/com/spring/myapp/MyappApplication.java
  src/main/java/com/spring/myapp/config/S3Config.java
  src/main/java/com/spring/myapp/product/controller/ProductController.java
  src/main/java/com/spring/myapp/product/controller/ProductImageController.java
  src/main/java/com/spring/myapp/product/controller/S3FileUploadController.java
  src/main/java/com/spring/myapp/product/model/Product.java
  src/main/java/com/spring/myapp/product/model/ProductImage.java
  src/main/java/com/spring/myapp/product/repository/ProductImageMapper.java
  src/main/java/com/spring/myapp/product/repository/ProductMapper.java
  src/main/java/com/spring/myapp/product/service/ProductImageService.java
  src/main/java/com/spring/myapp/product/service/ProductService.java
  src/main/java/com/spring/myapp/product/service/S3Service.java
  src/main/reactfront/src/pages/administrator/ItemListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemRegisterPage.tsx
  src/main/reactfront/src/types/DataInterface.tsx
  src/main/resources/mapper/product/ProductImageMapper.xml
  src/main/resources/mapper/product/ProductMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/resources/static/index.html
Labels: ✨ Feature

#122 ✨ Feat: 구글 OAuth2 로그인 API 구현 및 네이버/카카오 통합 설정 #114
  build.gradle
  src/main/java/com/spring/myapp/config/SecurityConfig.java
  src/main/java/com/spring/myapp/security/JwtTokenProvider.java
  src/main/java/com/spring/myapp/user/controller/UserController.java
  src/main/java/com/spring/myapp/user/model/UserSocialLogin.java
  src/main/java/com/spring/myapp/user/repository/UserMapper.java
  src/main/java/com/spring/myapp/user/repository/UserSocialLoginMapper.java
  src/main/java/com/spring/myapp/user/service/CustomOAuth2UserService.java
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/pages/signin/SigninPage.tsx
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/mapper/user/UserSocialLoginMapper.xml
  src/main/resources/static/index.html
Labels: ✨ Feature

#125 ♻️ Refactor: 관리자페이지 라우터 경로 수정 #123
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/pages/administrator/CommunityListPage.tsx
  src/main/reactfront/src/pages/administrator/EtcInquiryListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemInquiryListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemRegisterPage.tsx
  src/main/reactfront/src/pages/administrator/MemberListPage.tsx
  src/main/reactfront/src/pages/administrator/PostListPage.tsx
  src/main/reactfront/src/pages/administrator/ReviewListPage.tsx
Labels: 🎨 Style, ♻️ Refactor, 💄 Design

#128 🔥 Remove: package-lock.json 파일 삭제
  package-lock.json
Labels: 📃 Docs

#130 ♻️ Refactor: 카드리스트 컴포넌트 수정
  src/main/reactfront/src/components/cardList/CardList.tsx
  src/main/reactfront/src/components/contentCard/ContentCard.tsx
  src/main/reactfront/src/components/swiper/SwiperList.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
  src/main/reactfront/src/types/MainDummyData.ts
Labels: 🎨 Style, ♻️ Refactor

#133 ✨ Feat: JWT 토큰 페이로드에 userId와 name 추가 #132
  src/main/java/com/spring/myapp/security/JwtAuthenticationResponse.java
  src/main/java/com/spring/myapp/security/JwtTokenProvider.java
  src/main/java/com/spring/myapp/user/controller/NaverAuthController.java
  src/main/java/com/spring/myapp/user/controller/UserController.java
  src/main/java/com/spring/myapp/user/service/GoogleAuthService.java
  src/main/java/com/spring/myapp/user/service/KakaoAuthService.java
  src/main/java/com/spring/myapp/user/service/NaverAuthService.java
  src/main/reactfront/src/components/googleLogin/GoogleLoginButton.tsx
  src/main/reactfront/src/components/kakaoLogin/KakaoLoginButton.tsx
  src/main/reactfront/src/components/naverLogin/LoginSuccess.tsx
  src/main/reactfront/src/context/AuthContext.tsx
  src/main/reactfront/src/pages/signin/SigninPage.tsx
  src/main/resources/static/index.html
Labels: ✨ Feature

#134 ✨ Feature: 상품CRUD 및 장바구니 CR
  src/main/java/com/spring/myapp/cart/controller/CartController.java
  src/main/java/com/spring/myapp/cart/model/Cart.java
  src/main/java/com/spring/myapp/cart/model/CartItem.java
  src/main/java/com/spring/myapp/cart/repository/CartItemMapper.java
  src/main/java/com/spring/myapp/cart/repository/CartMapper.java
  src/main/java/com/spring/myapp/cart/service/CartService.java
  src/main/java/com/spring/myapp/product/controller/ProductController.java
  src/main/java/com/spring/myapp/product/controller/ProductImageController.java
  src/main/java/com/spring/myapp/product/model/Product.java
  src/main/java/com/spring/myapp/product/repository/ProductImageMapper.java
  src/main/java/com/spring/myapp/product/repository/ProductMapper.java
  src/main/java/com/spring/myapp/product/service/ProductImageService.java
  src/main/java/com/spring/myapp/product/service/ProductService.java
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/productCard/ProductCard.tsx
  src/main/reactfront/src/components/productDetail/ImageDetail.tsx
  src/main/reactfront/src/components/productDetail/ProductExplain.tsx
  src/main/reactfront/src/components/productDetail/PurchasePanel.tsx
  src/main/reactfront/src/pages/administrator/ItemListPage.tsx
  src/main/reactfront/src/pages/administrator/ItemUpdatePage.tsx
  src/main/reactfront/src/pages/mall/Fittness.tsx
  src/main/reactfront/src/pages/mall/Food.tsx
  src/main/reactfront/src/pages/mall/Mall.tsx
  src/main/reactfront/src/pages/mall/ProductCardList.tsx
  src/main/reactfront/src/pages/mall/Products.tsx
  src/main/reactfront/src/pages/mall/Supplemnet.tsx
  src/main/reactfront/src/pages/productDetail/ProductDetail.tsx
  src/main/reactfront/src/pages/shoppingBasket/ShoppingBasketPage.tsx
  src/main/reactfront/src/types/DataInterface.tsx
  src/main/resources/mapper/cart/CartItemMapper.xml
  src/main/resources/mapper/cart/CartMapper.xml
  src/main/resources/mapper/product/ProductImageMapper.xml
  src/main/resources/mapper/product/ProductMapper.xml
  src/main/resources/static/index.html
Labels: ✨ Feature, ♻️ Refactor

#136 ✨ Feat: 사이드바에 로그인 상태에 따른 사용자 정보 표시 및 로그아웃 기능 추가 #135
  src/main/reactfront/src/components/layout/sideNavBar/SideNavbar.tsx
  src/main/resources/static/index.html
Labels: ✨ Feature

#138 ✨ Feat: 운동 정보 게시판 CR #119
  src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardCommentsController.java
  src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardController.java
  src/main/java/com/spring/myapp/informationBoard/model/Category.java
  src/main/java/com/spring/myapp/informationBoard/model/Comments.java
  src/main/java/com/spring/myapp/informationBoard/model/Information.java
  src/main/java/com/spring/myapp/informationBoard/model/Likes.java
  src/main/java/com/spring/myapp/informationBoard/repository/InfoCommentsMapper.java
  src/main/java/com/spring/myapp/informationBoard/repository/InfoLikesMapper.java
  src/main/java/com/spring/myapp/informationBoard/repository/InfoMapper.java
  src/main/java/com/spring/myapp/informationBoard/service/InfoCommentsService.java
  src/main/java/com/spring/myapp/informationBoard/service/InfoLikesService.java
  src/main/java/com/spring/myapp/informationBoard/service/InfoS3Service.java
  src/main/java/com/spring/myapp/informationBoard/service/InfoService.java
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/common/comment/CommentInputField.styles.ts
  src/main/reactfront/src/components/common/comment/CommentInputField.tsx
  src/main/reactfront/src/components/common/comment/CommentList.tsx
  src/main/reactfront/src/components/common/comment/CommentListItem.tsx
  src/main/reactfront/src/components/common/comment/EditCommentInput.tsx
  src/main/reactfront/src/components/common/comment/StyledCommentItem.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.tsx
  src/main/reactfront/src/pages/administrator/PostRegisterPage.tsx
  src/main/reactfront/src/pages/information/Info.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
  src/main/reactfront/src/styles/common/TopBtn.ts
  src/main/reactfront/src/styles/information/Info.styles.ts
  src/main/reactfront/src/styles/information/InfoDetail.styles.ts
  src/main/reactfront/src/types/MainDummyData.ts
  src/main/resources/mapper/informationBoard/InfoCommentsMapper.xml
  src/main/resources/mapper/informationBoard/InfoLikesMapper.xml
  src/main/resources/mapper/informationBoard/InfoMapper.xml
  src/main/resources/static/index.html
Labels: ✨ Feature, ♻️ Refactor

#139 ✨ Feat: 루틴게시판 CRUD 구현 #117
  src/main/java/com/spring/myapp/routineBoard/controller/RoutineBoardController.java
  src/main/java/com/spring/myapp/routineBoard/model/RoutineBoard.java
  src/main/java/com/spring/myapp/routineBoard/model/RoutineGoal.java
  src/main/java/com/spring/myapp/routineBoard/model/RoutineLevel.java
  src/main/java/com/spring/myapp/routineBoard/model/RoutinePart.java
  src/main/java/com/spring/myapp/routineBoard/repository/RoutineBoardMapper.java
  src/main/java/com/spring/myapp/routineBoard/service/RoutineBoardService.java
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/cardList/CardList.tsx
  src/main/reactfront/src/components/common/Editor.tsx
  src/main/reactfront/src/components/common/button/ButtonNewRoutine.tsx
  src/main/reactfront/src/components/common/comment/CommentList.tsx
  src/main/reactfront/src/components/contentCard/ContentCard.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.tsx
  src/main/reactfront/src/components/routine/RoutineBestList.tsx
  src/main/reactfront/src/components/routine/RoutineTotalList.tsx
  src/main/reactfront/src/pages/community/ViewPostDetail.tsx
  src/main/reactfront/src/pages/mypage/MyRoutinePage.tsx
  src/main/reactfront/src/pages/routine/NewRoutine.tsx
  src/main/reactfront/src/pages/routine/RoutineMain.tsx
  src/main/reactfront/src/pages/routine/ViewRoutineDetail.tsx
  src/main/resources/mapper/routine/RoutineBoardMapper.xml
Labels: ✨ Feature

#145 ✨ feature : 커뮤니티 게시판 CRUD
  src/main/java/com/spring/myapp/community/controller/CommunityBoardController.java
  src/main/java/com/spring/myapp/community/dto/CommunityBoardDTO.java
  src/main/java/com/spring/myapp/community/model/CommunityBoardUserDetails.java
  src/main/java/com/spring/myapp/community/repository/CommunityBoardMapper.java
  src/main/java/com/spring/myapp/community/repository/CommunityBoardUser.java
  src/main/java/com/spring/myapp/community/repository/CommunityBoardUserRepository.java
  src/main/java/com/spring/myapp/community/service/CommunityBoardService.java
  src/main/java/com/spring/myapp/community/service/CommunityBoardUserDetailsService.java
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/community/Board.tsx
  src/main/reactfront/src/components/community/CommunityPostDetail.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.styles.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.tsx
  src/main/reactfront/src/context/UseAuth.ts
  src/main/reactfront/src/pages/community/CommunityPostEdit.tsx
  src/main/reactfront/src/pages/community/NewPost.tsx
  src/main/reactfront/src/pages/community/ViewPostDetail.tsx
  src/main/resources/mapper/community/CommunityBoardMapper.xml
  src/main/resources/static/index.html
Labels: ✨ Feature, ♻️ Refactor, 💄 Design

#146 🐛 Fix: 운동 정보글 등록 안되는 에러 해결 #140
  src/main/java/com/spring/myapp/informationBoard/service/InfoService.java
  src/main/reactfront/src/components/contentCard/ContentCard.tsx
  src/main/reactfront/src/pages/mypage/UserInfoPage.tsx
  src/main/resources/static/index.html
Labels: 🐛 BugFix, ♻️ Refactor

#156 ✅ Test: 커뮤니티 게시판 기능 테스트 및 수정
  src/main/reactfront/src/components/common/button/ButtonCategoryTag.tsx
  src/main/reactfront/src/components/community/Board.tsx
  src/main/reactfront/src/components/main/community/MainCommuity.tsx
  src/main/reactfront/src/types/MainDummyData.ts
Labels: ♻️ Refactor, ✅ Test

#157 ✅ Test: 마이페이지 테스트 #147
  src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardController.java
  src/main/reactfront/src/assets/img1.jpg
  src/main/reactfront/src/assets/img2.jpg
  src/main/reactfront/src/assets/img3.jpg
  src/main/reactfront/src/pages/mypage/CommentManagementPage.tsx
  src/main/reactfront/src/pages/mypage/MyHome.tsx
  src/main/reactfront/src/pages/mypage/MyRoutinePage.tsx
  src/main/reactfront/src/pages/mypage/MyRoutinesPage.tsx
  src/main/reactfront/src/pages/mypage/OneToOneInquiryPage.tsx
  src/main/reactfront/src/pages/mypage/OrderHistoryPage.tsx
  src/main/reactfront/src/pages/mypage/PostManagementPage.tsx
  src/main/reactfront/src/pages/mypage/ProductInquiryPage.tsx
  src/main/reactfront/src/pages/mypage/ProductReviewPage.tsx
  src/main/reactfront/src/pages/mypage/ReturnAndExchangePage.tsx
  src/main/reactfront/src/pages/mypage/ShippingAddressPage.tsx
  src/main/reactfront/src/pages/mypage/UserInfoLoginPage.tsx
  src/main/reactfront/src/pages/mypage/UserInfoPage.tsx
Labels: ♻️ Refactor, ✅ Test

#160 ✅ Test: 상품 페이지 테스트
  src/main/reactfront/src/components/productDetail/BasicRating.tsx
  src/main/reactfront/src/components/productDetail/PurchasePanel.tsx
  src/main/reactfront/src/components/tab/ReviewCombine.tsx
  src/main/reactfront/src/pages/mall/Mall.tsx
Labels: ♻️ Refactor, ✅ Test, 💄 Design

#162 ✅ Test: 관리자 페이지 테스트
  src/main/reactfront/src/components/calendar/Calendar.tsx
  src/main/reactfront/src/components/contentCard/ContentCard.styles.ts
  src/main/reactfront/src/components/productDetail/ImageDetail.tsx
  src/main/reactfront/src/pages/information/Info.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
  src/main/reactfront/src/pages/mall/Mall.tsx
  src/main/reactfront/src/types/administrator/InformationData.tsx
  src/main/reactfront/src/types/administrator/membersData.tsx
  src/main/resources/mapper/product/ProductMapper.xml
Labels: ♻️ Refactor, ✅ Test

#163 ✅Test를 위한 branch 생성 #153
  src/main/java/com/spring/myapp/routineBoard/controller/RoutineBoardController.java
  src/main/java/com/spring/myapp/routineBoard/service/RoutineBoardService.java
  src/main/reactfront/src/assets/img/main/routine1.jpg
  src/main/reactfront/src/assets/img/main/routine2.jpg
  src/main/reactfront/src/assets/img/main/routine3.jpg
  src/main/reactfront/src/assets/img/routine/Apsan.webp
  src/main/reactfront/src/assets/img/routine/chest.png
  src/main/reactfront/src/assets/img/routine/frontdouble.jpg
  src/main/reactfront/src/assets/img/routine/myroutine.jpg
  src/main/reactfront/src/assets/img/routine/routine1.jpg
  src/main/reactfront/src/assets/img/routine/routine10.jpg
  src/main/reactfront/src/assets/img/routine/routine11.jpg
  src/main/reactfront/src/assets/img/routine/routine12.jpg
  src/main/reactfront/src/assets/img/routine/routine2.jpg
  src/main/reactfront/src/assets/img/routine/routine3.jpg
  src/main/reactfront/src/assets/img/routine/routine4.jpg
  src/main/reactfront/src/assets/img/routine/routine5.jpg
  src/main/reactfront/src/assets/img/routine/routine6.jpg
  src/main/reactfront/src/assets/img/routine/routine7.jpg
  src/main/reactfront/src/assets/img/routine/routine8.jpg
  src/main/reactfront/src/assets/img/routine/routine9.jpg
  src/main/reactfront/src/components/main/routine/MainRoutines.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.tsx
  src/main/reactfront/src/components/routine/RoutineBestList.tsx
  src/main/reactfront/src/components/routine/RoutineTotalList.tsx
  src/main/reactfront/src/pages/routine/RoutineMain.tsx
  src/main/reactfront/src/pages/routine/ViewRoutineDetail.tsx
  src/main/reactfront/src/types/MainDummyData.ts
  src/main/resources/static/index.html
Labels: 💄 Design
