Repository suover/fit-on, pull requests merged in 2024-07, with the labels that each got.

#172 🐛 Fix: 로그인 실패 시 무한 쿼리 실행 문제 해결
  src/main/java/com/spring/myapp/config/SecurityConfig.java
  src/main/resources/static/index.html
Labels: 🐛 BugFix

#174 🐛 Fix 특정 페이지에서 새로고침 시 404 오류 및 유효하지 않은 경로에서 헤더와 푸터가 표시되는 문제 해결
  src/main/java/com/spring/myapp/config/WebConfig.java
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/pages/mall/Supplement.tsx
  src/main/reactfront/src/pages/notFound/NotFound.tsx
  src/main/resources/static/index.html
Labels: 🐛 BugFix

#176 ✨ Feat: 운동 정보 게시판 리팩토링 #168
  build.gradle
  src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardController.java
  src/main/java/com/spring/myapp/informationBoard/model/InfoPaging.java
  src/main/java/com/spring/myapp/informationBoard/model/Likes.java
  src/main/java/com/spring/myapp/informationBoard/repository/InfoLikesMapper.java
  src/main/java/com/spring/myapp/informationBoard/repository/InfoMapper.java
  src/main/java/com/spring/myapp/informationBoard/service/InfoLikesService.java
  src/main/java/com/spring/myapp/informationBoard/service/InfoService.java
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/common/comment/CommentInputField.tsx
  src/main/reactfront/src/components/common/comment/CommentListItem.tsx
  src/main/reactfront/src/components/contentCard/ContentCard.styles.ts
  src/main/reactfront/src/pages/administrator/PostRegisterPage.tsx
  src/main/reactfront/src/pages/information/Info.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
  src/main/reactfront/src/styles/information/Info.styles.ts
  src/main/reactfront/src/styles/information/InfoDetail.styles.ts
  src/main/resources/mapper/informationBoard/InfoLikesMapper.xml
  src/main/resources/mapper/informationBoard/InfoMapper.xml
  src/main/resources/static/index.html
Labels: ✨ Feature, 🎨 Style, ♻️ Refactor

#181 ✨ Feat: CORS 설정과 JWT 인증 흐름 개선 및 토큰 관리 로직 추가
  src/main/java/com/spring/myapp/config/SecurityConfig.java
  src/main/java/com/spring/myapp/config/WebConfig.java
  src/main/java/com/spring/myapp/security/JwtAuthenticationFilter.java
  src/main/java/com/spring/myapp/security/JwtAuthenticationResponse.java
  src/main/java/com/spring/myapp/security/JwtTokenProvider.java
  src/main/java/com/spring/myapp/user/controller/GoogleAuthController.java
  src/main/java/com/spring/myapp/user/controller/KakaoAuthController.java
  src/main/java/com/spring/myapp/user/controller/NaverAuthController.java
  src/main/java/com/spring/myapp/user/controller/UserController.java
  src/main/java/com/spring/myapp/user/service/AuthService.java
  src/main/java/com/spring/myapp/user/service/GoogleAuthService.java
  src/main/java/com/spring/myapp/user/service/KakaoAuthService.java
  src/main/java/com/spring/myapp/user/service/NaverAuthService.java
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/api/axiosConfig.ts
  src/main/reactfront/src/components/common/PrivateRoute.tsx
  src/main/reactfront/src/components/googleLogin/GoogleLoginButton.tsx
  src/main/reactfront/src/components/kakaoLogin/KakaoLoginButton.tsx
  src/main/reactfront/src/components/layout/header/Header.tsx
  src/main/reactfront/src/components/naverLogin/LoginSuccess.tsx
  src/main/reactfront/src/context/AuthContext.tsx
  src/main/reactfront/src/pages/signin/SigninPage.tsx
  src/main/reactfront/src/pages/signup/SignupPage.tsx
Labels: ⚙ Setting, ✨ Feature, 🐛 BugFix, 📬 API, ♻️ Refactor

#184 ♻️ Refactor: JWT 클레임 키를 camelCase로 업데이트
  src/main/java/com/spring/myapp/security/JwtTokenProvider.java
Labels: ♻️ Refactor

#188 ✨ Feat: 마이페이지 마이 홈 사용자 통계 조회 기능 추가
  src/main/java/com/spring/myapp/mypage/controller/MyHomeController.java
  src/main/java/com/spring/myapp/mypage/model/MyHomeStatistics.java
  src/main/java/com/spring/myapp/mypage/repository/MyHomeRepository.java
  src/main/java/com/spring/myapp/mypage/service/MyHomeService.java
  src/main/reactfront/src/pages/mypage/MyHome.tsx
  src/main/resources/mapper/mypage/MyHomeMapper.xml
Labels: ✨ Feature

#187 ✨장바구니 기능 및 쇼핑몰 페이지 보완
  src/main/java/com/spring/myapp/cart/controller/CartController.java
  src/main/java/com/spring/myapp/cart/repository/CartItemMapper.java
  src/main/java/com/spring/myapp/cart/repository/CartMapper.java
  src/main/java/com/spring/myapp/cart/service/CartService.java
  src/main/java/com/spring/myapp/product/controller/ProductController.java
  src/main/java/com/spring/myapp/product/controller/ProductImageController.java
  src/main/java/com/spring/myapp/product/repository/ProductImageMapper.java
  src/main/java/com/spring/myapp/product/repository/ProductMapper.java
  src/main/java/com/spring/myapp/product/service/ProductImageService.java
  src/main/java/com/spring/myapp/product/service/ProductService.java
  src/main/reactfront/src/components/productDetail/ImageDetail.tsx
  src/main/reactfront/src/components/productDetail/PurchasePanel.tsx
  src/main/reactfront/src/pages/mall/Mall.tsx
  src/main/reactfront/src/pages/order/OrderPage.tsx
  src/main/reactfront/src/pages/shoppingBasket/ShoppingBasketPage.tsx
  src/main/resources/mapper/cart/CartItemMapper.xml
  src/main/resources/mapper/product/ProductImageMapper.xml
  src/main/resources/mapper/product/ProductMapper.xml
  src/main/resources/static/index.html
Labels: ✨ Feature, ♻️ Refactor

#194 ✨ Feat: 쇼핑몰 검색 및 분류 , 페이징 기능
  src/main/java/com/spring/myapp/product/controller/ProductController.java
  src/main/java/com/spring/myapp/product/controller/ProductImageController.java
  src/main/java/com/spring/myapp/product/repository/ProductMapper.java
  src/main/java/com/spring/myapp/product/service/ProductService.java
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/layout/header/Header.tsx
  src/main/reactfront/src/components/productCard/ProductCard.styles.ts
  src/main/reactfront/src/pages/administrator/ItemRegisterPage.tsx
  src/main/reactfront/src/pages/mall/Fittness.tsx
  src/main/reactfront/src/pages/mall/Food.tsx
  src/main/reactfront/src/pages/mall/Mall.tsx
  src/main/reactfront/src/pages/mall/ProductCardList.tsx
  src/main/reactfront/src/pages/mall/Supplement.tsx
  src/main/reactfront/src/pages/productDetail/ProductDetail.tsx
  src/main/reactfront/src/types/DataInterface.tsx
  src/main/resources/mapper/product/ProductMapper.xml
Labels: ✨ Feature, ♻️ Refactor

#200 ✨ Feature: 상품 배송지
  src/main/java/com/spring/myapp/order/model/Order.java
  src/main/java/com/spring/myapp/order/repository/OrderMapper.java
  src/main/java/com/spring/myapp/order/service/OrderService.java
  src/main/java/com/spring/myapp/product/controller/ProductController.java
  src/main/java/com/spring/myapp/shipping/controller/ShippingAddressController.java
  src/main/java/com/spring/myapp/shipping/model/ShippingAddress.java
  src/main/java/com/spring/myapp/shipping/repository/ShippingAddressMapper.java
  src/main/java/com/spring/myapp/shipping/service/ShippingAddressService.java
  src/main/reactfront/src/pages/order/OrderPage.tsx
  src/main/reactfront/src/types/DataInterface.tsx
  src/main/resources/mapper/shippingAddress/ShippingAddress.xml
Labels: ⚙ Setting, ✨ Feature, ♻️ Refactor, 💄 Design

#204 ✨ Feat: 마이페이지 회원정보 기능 구현
  src/main/java/com/spring/myapp/mypage/controller/UserInfoController.java
  src/main/java/com/spring/myapp/mypage/dto/DeactivateAccountDTO.java
  src/main/java/com/spring/myapp/mypage/dto/PasswordUpdateDTO.java
  src/main/java/com/spring/myapp/mypage/dto/UserInfoAdditionalUpdateDTO.java
  src/main/java/com/spring/myapp/mypage/dto/UserInfoUpdateDTO.java
  src/main/java/com/spring/myapp/mypage/model/MyHomeStatistics.java
  src/main/java/com/spring/myapp/mypage/model/UserInfo.java
  src/main/java/com/spring/myapp/mypage/repository/UserInfoRepository.java
  src/main/java/com/spring/myapp/mypage/service/UserInfoService.java
  src/main/java/com/spring/myapp/security/JwtAuthenticationFilter.java
  src/main/reactfront/src/components/layout/sideNavBar/SideNavbar.tsx
  src/main/reactfront/src/components/layout/sideNavBar/StyledPersonIcon.tsx
  src/main/reactfront/src/context/AuthContext.tsx
  src/main/reactfront/src/pages/mypage/MyHome.tsx
  src/main/reactfront/src/pages/mypage/UserInfoLoginPage.tsx
  src/main/reactfront/src/pages/mypage/UserInfoPage.tsx
  src/main/reactfront/src/styles/mypage/UserInfoPage.styles.ts
  src/main/resources/mapper/mypage/UserInfoMapper.xml
Labels: ✨ Feature

#206 ✨ Feat: 운동 정보 페이지 검색 기능 구현 #193
  src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardCommentsController.java
  src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardController.java
  src/main/java/com/spring/myapp/informationBoard/repository/InfoMapper.java
  src/main/java/com/spring/myapp/informationBoard/service/InfoService.java
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/cardList/CardList.tsx
  src/main/reactfront/src/components/common/Editor.tsx
  src/main/reactfront/src/components/common/comment/CommentInputField.styles.ts
  src/main/reactfront/src/components/common/comment/CommentInputField.tsx
  src/main/reactfront/src/components/common/comment/CommentList.tsx
  src/main/reactfront/src/components/common/comment/CommentListItem.tsx
  src/main/reactfront/src/components/common/comment/EditCommentInput.tsx
  src/main/reactfront/src/components/common/comment/StyledCommentItem.styles.ts
  src/main/reactfront/src/components/common/comment/StyledCommentItem.tsx
  src/main/reactfront/src/components/layout/header/Header.tsx
  src/main/reactfront/src/pages/information/Info.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
  src/main/reactfront/src/styles/information/Info.styles.ts
  src/main/resources/mapper/informationBoard/InfoMapper.xml
Labels: ✨ Feature, ♻️ Refactor, 💄 Design

#208 ✨ Feat: 마이페이지 회원정보 회원 프로필 이미지 업로드 기능 구현
  src/main/java/com/spring/myapp/mypage/controller/UserInfoController.java
  src/main/java/com/spring/myapp/mypage/model/UserInfo.java
  src/main/java/com/spring/myapp/mypage/repository/UserInfoRepository.java
  src/main/java/com/spring/myapp/mypage/service/UserInfoService.java
  src/main/reactfront/src/components/common/profileImage/ProfileImage.tsx
  src/main/reactfront/src/components/layout/sideNavBar/SideNavbar.tsx
  src/main/reactfront/src/components/layout/sideNavBar/StyledProfileImage.tsx
  src/main/reactfront/src/pages/mypage/MyHome.tsx
  src/main/reactfront/src/pages/mypage/UserInfoPage.tsx
  src/main/resources/mapper/mypage/UserInfoMapper.xml
Labels: ✨ Feature

#211 Refactor : 댓글 route 수정 및 커뮤니티 게시판 카테고리 버튼 필터 수정 #210
  src/main/java/com/spring/myapp/community/controller/CommunityBoardCommentController.java
  src/main/java/com/spring/myapp/community/controller/CommunityBoardController.java
  src/main/java/com/spring/myapp/community/dto/CommunityBoardCommentDTO.java
  src/main/java/com/spring/myapp/community/model/CommunityBoardUserDetails.java
  src/main/java/com/spring/myapp/community/service/CommunityBoardCommentService.java
  src/main/java/com/spring/myapp/community/service/CommunityBoardService.java
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/common/SelectBox.tsx
  src/main/reactfront/src/components/common/button/ButtonCategoryTag.tsx
  src/main/reactfront/src/components/community/Board.tsx
  src/main/reactfront/src/pages/community/CommunityMain.tsx
  src/main/reactfront/src/pages/community/CommunityPostEdit.tsx
  src/main/reactfront/src/pages/community/NewPost.tsx
  src/main/reactfront/src/pages/community/ViewPostDetail.tsx
Labels: ✨ Feature, ♻️ Refactor

#212 ✨ Feature: 상품 주문 및 결제 #201
  build.gradle
  src/main/java/com/spring/myapp/order/controller/OrderController.java
  src/main/java/com/spring/myapp/order/model/Order.java
  src/main/java/com/spring/myapp/order/model/OrderItems.java
  src/main/java/com/spring/myapp/order/model/OrderRequest.java
  src/main/java/com/spring/myapp/order/repository/OrderItemMapper.java
  src/main/java/com/spring/myapp/order/repository/OrderMapper.java
  src/main/java/com/spring/myapp/order/service/OrderService.java
  src/main/java/com/spring/myapp/payment/controller/PaymentController.java
  src/main/java/com/spring/myapp/payment/service/PaymentService.java
  src/main/java/com/spring/myapp/product/model/Product.java
  src/main/reactfront/package-lock.json
  src/main/reactfront/package.json
  src/main/reactfront/src/components/order/Radio.tsx
  src/main/reactfront/src/pages/administrator/ItemListPage.tsx
  src/main/reactfront/src/pages/order/OrderPage.tsx
  src/main/reactfront/src/styles/order/Order.Styles.ts
  src/main/resources/mapper/order/OrderItemMapper.xml
  src/main/resources/mapper/order/OrderMapper.xml
Labels: ✨ Feature, ♻️ Refactor

#216 ✨ Feat: 메인 페이지 기능 구현 #207
  src/main/java/com/spring/myapp/home/controller/HomeController.java
  src/main/java/com/spring/myapp/home/dto/HomeDTO.java
  src/main/java/com/spring/myapp/home/repository/HomeMapper.java
  src/main/java/com/spring/myapp/home/service/HomeService.java
  src/main/java/com/spring/myapp/informationBoard/controller/InfoBoardCommentsController.java
  src/main/reactfront/src/components/ListTable/StyledColumn.styles.ts
  src/main/reactfront/src/components/common/comment/StyledCommentItem.tsx
  src/main/reactfront/src/components/community/Board.tsx
  src/main/reactfront/src/components/layout/header/Header.tsx
  src/main/reactfront/src/components/listTable/ListTable.tsx
  src/main/reactfront/src/components/listTable/StyledColumn.styles.ts
  src/main/reactfront/src/components/main/bestItems/BestItems.styles.ts
  src/main/reactfront/src/components/main/bestItems/BestItems.tsx
  src/main/reactfront/src/components/main/community/MainCommuity.tsx
  src/main/reactfront/src/components/main/info/MainInfo.tsx
  src/main/reactfront/src/components/main/quickBtn/QuickBtns.tsx
  src/main/reactfront/src/components/main/routine/MainRoutines.styles.ts
  src/main/reactfront/src/components/main/routine/MainRoutines.tsx
  src/main/reactfront/src/components/main/routine/RoutineList.styles.ts
  src/main/reactfront/src/components/main/routine/RoutineList.tsx
  src/main/reactfront/src/components/postDetail/PostDetail.tsx
  src/main/reactfront/src/components/productItem/ProductItem.tsx
  src/main/reactfront/src/components/swiper/SwiperList.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
  src/main/reactfront/src/pages/main/Main.tsx
  src/main/reactfront/src/styles/information/InfoDetail.styles.ts
  src/main/reactfront/src/types/MainDummyData.ts
  src/main/resources/mapper/home/HomeMapper.xml
  src/main/resources/mapper/informationBoard/InfoMapper.xml
Labels: ✨ Feature, 💄 Design

#217 ✨ Feat: 마이페이지 게시글 관리 기능 구현
  src/main/java/com/spring/myapp/mypage/controller/PostManagementController.java
  src/main/java/com/spring/myapp/mypage/dto/PostManagementDto.java
  src/main/java/com/spring/myapp/mypage/repository/PostManagementRepository.java
  src/main/java/com/spring/myapp/mypage/service/PostManagementService.java
  src/main/reactfront/src/components/genericTable/GenericTable.tsx
  src/main/reactfront/src/pages/mypage/PostManagementPage.tsx
  src/main/resources/mapper/mypage/PostManagementMapper.xml
Labels: ✨ Feature

#218 ♻️ Refactor : Mall 디자인 및 기타 수정 사항
  src/main/java/com/spring/myapp/cart/controller/CartController.java
  src/main/reactfront/src/App.tsx
  src/main/reactfront/src/components/common/Editor.tsx
  src/main/reactfront/src/components/productCard/ProductCard.styles.ts
  src/main/reactfront/src/pages/administrator/AdminPage.tsx
  src/main/reactfront/src/pages/administrator/OrderManagementPage.tsx
  src/main/reactfront/src/pages/mall/Fittness.tsx
  src/main/reactfront/src/pages/mall/Food.tsx
  src/main/reactfront/src/pages/mall/MallMain.tsx
  src/main/reactfront/src/pages/mall/ProductCardList.tsx
  src/main/reactfront/src/pages/mall/Supplement.tsx
  src/main/reactfront/src/pages/shoppingBasket/ShoppingBasketPage.tsx
Labels: ✨ Feature, ♻️ Refactor

#223 🐛 Fix : 정보페이지 경로 관련 버그 수정 #222
  src/main/reactfront/src/components/main/info/MainInfo.tsx
  src/main/reactfront/src/components/main/routine/MainRoutines.tsx
  src/main/reactfront/src/pages/administrator/PostRegisterPage.tsx
  src/main/reactfront/src/pages/information/InfoDetail.tsx
Labels: 🐛 Bug, 🐛 BugFix
